version: '3'
services:
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: DockerFile-flask
    volumes:
      - "./:/app"
  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: DockerFile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask